enabled: 0
domain: 'https://www.worldwaterforum.org'
check_period: 10800
domain_check_retries: 3
domain_check_reenable: true
disabled_by_check: true
last_checked: 0
loop_max_redirects: 3
applicability: 0
pages: ''
_core:
  default_config_hash: NfxY0zFdNbYpKOQflIgL0r3BFkLa6C68jc5kAlrevho
redirect_last_checked: 1596672602
