smtp_on: false
smtp_host: ex3.mail.ovh.net
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_username: contact@worldwaterforum.org
smtp_password: GlOdorack21
smtp_from: contact@worldwaterforum.org
smtp_fromname: '9th World Water Forum'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
smtp_autotls: true
smtp_timeout: 30
smtp_keepalive: false
