breadcrumb_separator: fa-angle-right
scroll_to_top_display: 1
scroll_to_top_icon: fa-angle-up
bootstrap_remote_type: local
color_scheme: blue
page_container_border: 0
animations_state: 1
slideout_background_color: 'region--light-typography region--dark-background'
slideout_side: right
slideout_touch_swipe: 0
slideout_blocks_paddings: 0
slideout_region_paddings: 0
header_top_highlighted_layout_container: container
header_top_highlighted_background_color: 'region--light-typography region--black-background'
header_top_highlighted_animation_effect: fadeInUp
header_top_highlighted_blocks_paddings: 0
header_top_highlighted_region_paddings: 0
header_top_layout_container: container
header_top_background_color: 'region--dark-typography region--white-background region--white-pattern'
header_top_animation_effect: fadeIn
header_top_blocks_paddings: 1
header_top_region_paddings: 0
header_layout_container: container
header_background_color: 'region--dark-typography region--white-background region--white-pattern'
fixed_header: 0
header_blocks_paddings: 0
header_region_paddings: 0
header_background_image_state: 0
banner_layout_container: container-fluid
banner_background_color: 'region--dark-typography region--white-background'
banner_blocks_paddings: 1
banner_region_paddings: 1
content_top_layout_container: container
content_top_background_color: 'region--light-typography region--dark-background'
content_top_animation_effect: fadeInUp
content_top_blocks_paddings: 1
content_top_region_paddings: 1
content_top_highlighted_layout_container: container
content_top_highlighted_separator: region--no-separator
content_top_highlighted_background_color: 'region--dark-typography region--white-background'
content_top_highlighted_animation_effect: fadeInUp
content_top_highlighted_blocks_paddings: 0
content_top_highlighted_region_paddings: 0
main_content_separator: region--no-separator
main_content_animation_effect: fadeIn
main_content_blocks_paddings: 0
main_content_region_paddings: 0
sidebar_first_animation_effect: fadeIn
sidebar_first_blocks_paddings: 0
sidebar_first_region_paddings: 0
sidebar_second_animation_effect: fadeIn
sidebar_second_blocks_paddings: 0
sidebar_second_region_paddings: 0
content_bottom_layout_container: container
content_bottom_separator: region--no-separator
content_bottom_background_color: 'region--dark-typography region--white-background region--white-pattern'
content_bottom_animation_effect: fadeInDown
content_bottom_blocks_paddings: 1
content_bottom_region_paddings: 0
featured_top_layout_container: container
featured_top_separator: region--no-separator
featured_top_background_color: 'region--dark-typography region--white-background region--white-pattern'
featured_top_animation_effect: fadeInUp
featured_top_blocks_paddings: 0
featured_top_region_paddings: 0
featured_layout_container: container
featured_separator: region--no-separator
featured_background_color: 'region--dark-typography region--gray-background'
featured_animation_effect: fadeIn
featured_blocks_paddings: 0
featured_region_paddings: 0
featured_bottom_layout_container: container
featured_bottom_separator: region--no-separator
featured_bottom_background_color: 'region--dark-typography region--gray-background'
featured_bottom_animation_effect: no-animation
featured_bottom_blocks_paddings: 0
featured_bottom_region_paddings: 0
sub_featured_layout_container: container
sub_featured_separator: region--no-separator
sub_featured_background_color: 'region--light-typography region--dark-background'
sub_featured_animation_effect: fadeIn
sub_featured_blocks_paddings: 0
sub_featured_region_paddings: 0
highlighted_top_layout_container: container
highlighted_top_separator: region--no-separator
highlighted_top_background_color: 'region--dark-typography region--white-background'
highlighted_top_animation_effect: fadeIn
highlighted_top_blocks_paddings: 0
highlighted_top_region_paddings: 0
highlighted_layout_container: container
highlighted_separator: region--no-separator
highlighted_background_color: 'region--dark-typography region--gray-background'
highlighted_animation_effect: fadeIn
highlighted_blocks_paddings: 0
highlighted_region_paddings: 0
footer_top_layout_container: container
footer_top_separator: region--no-separator
footer_top_background_color: 'region--dark-typography region--gray-background'
footer_top_animation_effect: fadeInUp
footer_top_blocks_paddings: 0
footer_top_region_paddings: 0
footer_layout_container: container
footer_separator: region--no-separator
footer_background_color: 'region--light-typography region--dark-background'
footer_animation_effect: fadeIn
footer_blocks_paddings: 0
footer_region_paddings: 0
footer_bottom_layout_container: container
footer_bottom_separator: region--no-separator
footer_bottom_background_color: 'region--dark-typography region--white-background'
footer_bottom_blocks_paddings: 1
footer_bottom_region_paddings: 0
subfooter_layout_container: container
subfooter_separator: region--no-separator
subfooter_background_color: 'region--dark-typography region--white-background'
subfooter_bottom_blocks_paddings: false
subfooter_bottom_region_paddings: false
front_page_banner_separator_position: '0'
reading_time: 0
share_links: 1
share_links_print_position: bottom
print_button: 1
font_resize: 1
post_progress: 0
affix_side: 1
layout_mode: wide
headings_font_family: hff-09
headings_wide_spacing: 0
paragraph_font_family: pff-09
paragraph_responsive_typography: 1
sitename_font_family: sff-09
slogan_font_family: slff-09
rs_slideshow_fullscreen_effect: random
rs_slideshow_fullscreen_effect_time: '10'
rs_slideshow_fullscreen_navigation_style: bullets
rs_slideshow_fullscreen_bullets_position: right
rs_slideshow_fullscreen_touch_swipe: 1
transparent_header_state: 0
transparent_header_opacity: '0'
inverted_header_state: 0
rs_slideshow_fullwidth_effect: random
rs_slideshow_fullwidth_effect_time: '10'
rs_slideshow_fullwidth_initial_height: '650'
rs_slideshow_fullwidth_navigation_style: bullets
rs_slideshow_fullwidth_bullets_position: right
rs_slideshow_fullwidth_touch_swipe: 1
rs_slideshow_boxedwidth_effect: random
rs_slideshow_boxedwidth_effect_time: '10'
rs_slideshow_boxedwidth_initial_height: '650'
rs_slideshow_boxedwidth_navigation_style: titles_carousel
rs_slideshow_boxedwidth_bullets_position: right
rs_slideshow_boxedwidth_touch_swipe: 1
rs_slideshow_internal_effect: fade
rs_slideshow_internal_effect_time: '10'
rs_slideshow_internal_initial_height: '540'
rs_slideshow_internal_navigation_style: bullets
rs_slideshow_internal_banner_bullets_position: left
rs_slideshow_internal_touch_swipe: 1
rs_slideshow_internal_carousel_effect: fade
rs_slideshow_internal_carousel_initial_height: '540'
rs_slideshow_internal_carousel_bullets_position: center
rs_slideshow_internal_carousel_touch_swipe: 1
rs_slideshow_caption_opacity: '0'
rs_slideshow_background_opacity: '50'
in_page_slider_effect: slide
owl_products_autoplay: 1
owl_products_effect_time: '5'
owl_albums_autoplay: 1
owl_albums_effect_time: '5'
owl_team_members_autoplay: 0
owl_team_members_effect_time: '5'
owl_promoted_posts_autoplay: false
owl_promoted_posts_effect_time: '5'
owl_articles_autoplay: 0
owl_articles_effect_time: '5'
owl_testimonials_autoplay: 1
owl_testimonials_effect_time: '5'
owl_related_nodes_autoplay: 0
owl_related_nodes_effect_time: '5'
owl_collections_autoplay: 0
owl_collections_effect_time: '5'
in_page_navigation_offset: '74'
banner_id: banner
content_top_id: content-top
content_top_highlighted_id: content-top-highlighted
main_content_id: main-content
content_bottom_id: content-bottom
featured_top_id: featured-top
featured_id: featured
featured_bottom_id: featured-bottom
sub_featured_id: sub-featured
highlighted_top_id: highlighted-top
highlighted_id: highlighted
footer_top_id: footer-top
footer_id: footer
footer_bottom_id: footer-bottom
subfooter_id: subfooter
isotope_layout_mode: masonry
isotope_filters_text: All
google_maps_key: AIzaSyDyL-4KyWw_3hp-0jmZLGcJ3zMWkkJ44VI
_core:
  default_config_hash: 48vZvGR5PYgurZWHO_a0XwQY17t2eeRgUgotHETQPrY
features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 0
  path: 'public://favicon.png'
  mimetype: image/png
subfooter_blocks_paddings: 0
subfooter_region_paddings: 0
font_title: ''
rs_slideshow_internal_bullets_position: left
